allowBuilds:
  '@heroui/shared-utils': true
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true
  spawn-sync: true
  unrs-resolver: true
